<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Apabila3</name>
   <tag></tag>
   <elementGuidId>23c2a064-43dd-492b-90da-6f908f018f0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Apabila Anda membutuhkan informasi lebih lanjut mengenai Ketentuan Penggunaan Tanda Tangan Elektronik ini, silakan hubungi kami melalui e-mail: customercare@pintek.id atau pada nomor telepon: 021-50884607.' or . = 'Apabila Anda membutuhkan informasi lebih lanjut mengenai Ketentuan Penggunaan Tanda Tangan Elektronik ini, silakan hubungi kami melalui e-mail: customercare@pintek.id atau pada nomor telepon: 021-50884607.')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-tabs-0-panel-3']/div/div/p[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>normal-text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apabila Anda membutuhkan informasi lebih lanjut mengenai Ketentuan Penggunaan Tanda Tangan Elektronik ini, silakan hubungi kami melalui e-mail: customercare@pintek.id atau pada nomor telepon: 021-50884607.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-tabs-0-panel-3&quot;)/div[@class=&quot;section tnc-signature-modals text-left&quot;]/div[@class=&quot;container&quot;]/p[@class=&quot;normal-text&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-tabs-0-panel-3']/div/div/p[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pemberitahuan'])[1]/following::p[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='e-mail'])[1]/following::p[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setuju dan Lanjutkan'])[1]/preceding::p[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apabila Anda membutuhkan informasi lebih lanjut mengenai Ketentuan Penggunaan Tanda Tangan Elektronik ini, silakan hubungi kami melalui e-mail:']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/p[4]</value>
   </webElementXpaths>
</WebElementEntity>
